name: Deploy Next.js

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            echo "==> Prepare directory"
            mkdir -p /var/www

            echo "==> Clone repository"
            rm -rf /var/www/portofolio-web

            git clone git@github.com:${{ secrets.USERNAME }} /var/www/portofolio-web

            echo "==> Check deployment"
            cd /var/www/portofolio-web

            git rev-parse --short HEAD

            echo "==> Clone successful!"